update sync scripts

diff --git a/sync-cdargs b/sync-cdargs
--- a/sync-cdargs
+++ b/sync-cdargs
@@ -5,7 +5,7 @@
 # License: Public Domain
 
 if [[ ! -e ~/.cdargs ]]; then
-	echo "Unable to find file ~/.cdargs." 1>&2
+	echo "Unable to find file ~/.cdargs" 1>&2
 fi
 
 # mc {{{1
diff --git a/sync-warp b/sync-warp
--- a/sync-warp
+++ b/sync-warp
@@ -6,7 +6,7 @@
 # License: Public Domain
 
 if [[ ! -e ~/.warprc ]]; then
-	echo "Unable to find file ~/.cdargs." 1>&2
+	echo "Unable to find file ~/.warprc" 1>&2
 fi
 
 # mc {{{1
